version: '3.5'

services:

  nginx:
    image: nginx:alpine
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    restart: always
    ports:
      - "${WEB_PORT_HTTP}:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}-app
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
      - redis
      - mail
    networks:
      - laravel

  mysql:
    image: 'mysql:8.0'
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
    ports:
      - '3306:3306'
    volumes:
      - ~/var/mysql-data:/var/lib/mysql
    networks:
      - laravel

  adminer:
    image: adminer:latest
    container_name: ${COMPOSE_PROJECT_NAME}-adminer
    environment:
      ADMINER_DEFAULT_SERVER: ${COMPOSE_PROJECT_NAME}-mysql
    ports:
      - 8080:8080
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: ${COMPOSE_PROJECT_NAME}-redis
    ports:
      - "6379:6379"
    networks:
      - laravel

  mail:
    image: axllent/mailpit:latest
    container_name: ${COMPOSE_PROJECT_NAME}-mail
    restart: always
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - laravel

networks:
  laravel:
    name: laravel